In [27]:
import torch
from PIL import Image
import torch
import torch.nn as nn
import torch.utils.checkpoint as checkpoint
from timm.models.layers import DropPath, to_2tuple, trunc_normal_
from torchvision.models.resnet import resnet18
from torchvision.models import resnet101
from efficientnet_pytorch import EfficientNet
from torchvision import datasets, transforms
from data.fetal_loader import Fetal_frame
from models.effnetv2 import EffnetV2_L
import joblib

In [12]:
transform = transforms.Compose([transforms.Resize((450, 600)),
                transforms.Pad((0, 0, 0, 150), fill = 0, padding_mode = 'constant'),
                transforms.Resize((512, 512)),
                transforms.Normalize(mean=0.1354949, std=0.18222201)])

In [13]:
dataset = Fetal_frame(root = '/data/kpusteln/fetal/fetal_extracted/', 
                    ann_path = '/data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/biometry_test_scaled_size_subset.csv', 
                    transform = transform)

In [44]:
model = EffnetV2_L(in_channels = 1, out_features = 1)
path_to_model = '/data/kpusteln/Fetal-RL/swin-transformer/output/effnetv2_reg_l1_no_scaling_no_meta_drop04_new_lr_no_augm_no_sigm_avgpool/default/ckpt_epoch_47.pth'
checkpoint1 = torch.load(path_to_model, map_location='cpu')
msg1 = model.load_state_dict(checkpoint1['model'], strict=False)

In [45]:
data_loader_test = torch.utils.data.DataLoader(
    dataset, 
    batch_size=1,
    shuffle = False,
    drop_last = False)

In [46]:
model.eval()

EffnetV2_L(
  (model): EfficientNet(
    (features): Sequential(
      (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): Sequential(
        (0): FusedMBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.0, mode=row)
        )
        (1): FusedMBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
          )
          (stochastic_depth): Stochasti

In [47]:
scaler = joblib.load('/data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/normalizer_measure')

In [50]:
for idx, (images, Class, measure, ps, frames_n, measure_scaled, index, days_normalized, frame_loc, measure_normalized) in enumerate(data_loader_test):
        
    outputs = model(images)
    print(Class)
    print(measure)
    print(outputs)
    outputs = outputs.detach().cpu().numpy()
    ps = ps.detach().cpu().numpy()
    print(scaler.inverse_transform(outputs) * ps)
    print(measure_scaled)
    break

tensor([2])
tensor([20.1900], dtype=torch.float64)
tensor([[0.2395]], grad_fn=<AddmmBackward0>)
[[5.75576601]]
tensor([0.9684])


In [42]:
from PIL import Image
import torch
arr = images.permute(2, 0, 1).int().numpy()

# Create PIL image from array
im = Image.fromarray(arr)
 # open the image with the default viewer


TypeError: Cannot handle this data type: (1, 1, 512), <i4

In [1]:
lista = [1,2,3,4]

In [6]:
lista[3:4]

[4]

In [1]:
import pandas as pd
import torch

In [41]:
results = []
result = torch.tensor([1])
#result = result.numpy()
results.append(result)

In [43]:
results.extend(result)

In [46]:
results = torch.stack(results)

RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [] at entry 1

In [45]:
results = results.numpy()

AttributeError: 'list' object has no attribute 'numpy'

In [44]:
results

[tensor([1]), tensor(1), tensor(1)]

In [35]:
data = pd.DataFrame(results)

TypeError: iteration over a 0-d tensor

In [ ]:
data

0
0  1
1  1
2  1

In [9]:
data.to_csv('test.csv')

In [1]:
import pandas as pd